# Generated by Django 4.2.16 on 2024-11-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('running_batch', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programme_curriculum_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('working_curriculum', models.BooleanField(default=True)),
                ('no_of_semester', models.PositiveIntegerField(default=1)),
                ('min_credit', models.PositiveIntegerField(default=0)),
                ('latest_version', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programme_curriculum_curriculum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'academic_information_discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsDepartmentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'globals_departmentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'globals_designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsExtrainfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('user_status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(max_length=20)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.TextField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'globals_extrainfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsHoldsdesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'globals_holdsdesignation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalsModuleaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=155)),
                ('program_and_curriculum', models.BooleanField()),
                ('course_registration', models.BooleanField()),
                ('course_management', models.BooleanField()),
                ('other_academics', models.BooleanField()),
                ('spacs', models.BooleanField()),
                ('department', models.BooleanField()),
                ('examinations', models.BooleanField()),
                ('hr', models.BooleanField()),
                ('iwd', models.BooleanField()),
                ('complaint_management', models.BooleanField()),
                ('fts', models.BooleanField()),
                ('purchase_and_store', models.BooleanField()),
                ('rspc', models.BooleanField()),
                ('hostel_management', models.BooleanField()),
                ('mess_management', models.BooleanField()),
                ('gymkhana', models.BooleanField()),
                ('placement_cell', models.BooleanField()),
                ('visitor_hostel', models.BooleanField()),
                ('phc', models.BooleanField()),
            ],
            options={
                'db_table': 'globals_moduleaccess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('programme_begin_year', models.PositiveIntegerField(default=2024)),
            ],
            options={
                'db_table': 'programme_curriculum_programme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.globalsextrainfo')),
                ('programme', models.CharField(max_length=10)),
                ('batch', models.IntegerField(default=2016)),
                ('cpi', models.FloatField(default=0)),
                ('category', models.CharField(max_length=10)),
                ('father_name', models.CharField(default='', max_length=40, null=True)),
                ('mother_name', models.CharField(default='', max_length=40, null=True)),
                ('hall_no', models.IntegerField(default=0)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(default='', max_length=40, null=True)),
                ('curr_semester_no', models.IntegerField(default=1)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
        ),
    ]
