# Generated by Django 4.2.16 on 2024-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_authuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsdepartmentinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsdesignation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsextrainfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsholdsdesignation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalsmoduleaccess',
            options={'managed': True},
        ),
    ]
